CREATE TABLE account (
    id bigint generated by default as identity,
    account_number varchar(10) not null,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE transaction (
    id bigint generated by default as identity,
    source_account_id bigint not null,
    destination_account_id bigint not null,
    amount double not null,
    scheduler_date date not null,
    fee double not null,
    created_at timestamp default current_timestamp,
    CONSTRAINT pk_transaction PRIMARY KEY (id),
    CONSTRAINT fk_transaction_source_account FOREIGN KEY (source_account_id) REFERENCES account(id),
    CONSTRAINT fk_transaction_destination_account FOREIGN KEY (destination_account_id) REFERENCES account(id)
);
